spring:
  datasource:
    url: jdbc:mysql://192.168.8.100:3306/test_ldw?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson: 
    serialization: 
      indent_output: true

spring.profiles.active: prod

server:
  port: 8088